# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tiny_petstore.models.base_model_ import Model
from tiny_petstore.models.store import Store  # noqa: F401,E501
import re  # noqa: F401,E501
from tiny_petstore import util


class Pet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, store: Store=None, status: str='pending'):  # noqa: E501
        """Pet - a model defined in Swagger

        :param id: The id of this Pet.  # noqa: E501
        :type id: int
        :param name: The name of this Pet.  # noqa: E501
        :type name: str
        :param store: The store of this Pet.  # noqa: E501
        :type store: Store
        :param status: The status of this Pet.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'store': Store,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'store': 'store',
            'status': 'status'
        }

        self._id = id
        self._name = name
        self._store = store
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Pet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pet of this Pet.  # noqa: E501
        :rtype: Pet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Pet.


        :return: The id of this Pet.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Pet.


        :param id: The id of this Pet.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Pet.


        :return: The name of this Pet.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Pet.


        :param name: The name of this Pet.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and not re.search('^[A-Za-z0-9]', name):  # noqa: E501
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[A-Za-z0-9]/`")  # noqa: E501

        self._name = name

    @property
    def store(self) -> Store:
        """Gets the store of this Pet.


        :return: The store of this Pet.
        :rtype: Store
        """
        return self._store

    @store.setter
    def store(self, store: Store):
        """Sets the store of this Pet.


        :param store: The store of this Pet.
        :type store: Store
        """
        if store is None:
            raise ValueError("Invalid value for `store`, must not be `None`")  # noqa: E501

        self._store = store

    @property
    def status(self) -> str:
        """Gets the status of this Pet.

        pet status in the store  # noqa: E501

        :return: The status of this Pet.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Pet.

        pet status in the store  # noqa: E501

        :param status: The status of this Pet.
        :type status: str
        """
        allowed_values = ["available", "pending", "sold"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
