# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tiny_petstore.models.base_model_ import Model
import re  # noqa: F401,E501
from tiny_petstore import util


class StoreParam(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, address: str=None):  # noqa: E501
        """StoreParam - a model defined in Swagger

        :param name: The name of this StoreParam.  # noqa: E501
        :type name: str
        :param address: The address of this StoreParam.  # noqa: E501
        :type address: str
        """
        self.swagger_types = {
            'name': str,
            'address': str
        }

        self.attribute_map = {
            'name': 'name',
            'address': 'address'
        }

        self._name = name
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'StoreParam':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StoreParam of this StoreParam.  # noqa: E501
        :rtype: StoreParam
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this StoreParam.


        :return: The name of this StoreParam.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this StoreParam.


        :param name: The name of this StoreParam.
        :type name: str
        """
        if name is not None and not re.search('^[A-Za-z0-9]', name):  # noqa: E501
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[A-Za-z0-9]/`")  # noqa: E501

        self._name = name

    @property
    def address(self) -> str:
        """Gets the address of this StoreParam.


        :return: The address of this StoreParam.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this StoreParam.


        :param address: The address of this StoreParam.
        :type address: str
        """

        self._address = address
